@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.xalcon.flightboost.enchantments;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;